172 datetime
kontent-ai/model-generator-net pull request #173
Opened 2023-01-19 13:22 UTC by Sevitas

### Motivation

Which issue does this fix? Fixes #172 

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Generate structured elements for RT, DT. Generate elements without structured option.

2023-01-26 08:42 UTC, Simply007 requested changes
Let's try to avoid the breaking change. Leave the "True" value for the structured model as a possible solution, but **deprecated**.

* Once the user upgrade and uses `--structuredMode True` add logging that the value is deprecated
* Note that to readme as well (and ideally mark it by `System.Obsolete`)

2023-01-26 11:01 UTC, Sevitas commented
> Let's try to avoid the breaking change. Leave the "True" value for the structured model as a possible solution, but **deprecated**.
> 
> * Once the user upgrade and uses `--structuredMode True` add logging that the value is deprecated
> * Note that to readme as well (and ideally mark it by `System.Obsolete`)

Should be fixed.

2023-02-09 13:54 UTC, winklertomas requested changes

2023-02-09 13:54 UTC, winklertomas commented on README.md
> +- `KontentModelGenerator --projectid "<projectid>" [--namespace "<custom-namespace>"] [--outputdir "<output-directory>"] [--withtypeprovider <True|False>] [--structuredmodel <"{structured_model}"] [-
unnecessary quotation marks? You didn't use them in https://github.com/kontent-ai/delivery-sdk-net/pull/361/files

And missing '>'. The same applies to examples bellow

2023-02-09 14:10 UTC, winklertomas approved these changes
Review OK

2023-02-09 14:14 UTC, merged